### ISSUE TITLE
The syntax theme doesn't work in the latest version of Atom

### ISSUE THREAD

**Issue by gusbemacbe** [scottenriquez/atom-burnt-orange-syntax#1]
Hello,

I use Atom 1.19.3 and Atom Beta 1.20

I use Dash, One Dark, Pristine and Seti as UI theme, and I set Atom Burnt Orange as syntax theme, but the colours are different.

![screen shot 2017-08-22 at 20 31 02](https://user-images.githubusercontent.com/2257024/29592156-de3ffefe-8778-11e7-8c4c-0b1183dc31eb.png)

**Comment by gusbemacbe** [comment]
It seems that Atom reported many deprecated selectors in this theme:

![screen shot 2017-08-22 at 20 41 03](https://user-images.githubusercontent.com/2257024/29592432-44a7039e-877a-11e7-984d-fd70f41a8ff9.png)

**Comment by scottenriquez** [comment]
Hello, Gustavo!

Thanks for the heads up! I've been swamped with work, but I'll get the themes updated soon.
